### ISSUE TITLE
Errors in  layers/ETSformer_EncDec.py

### ISSUE THREAD

**Issue by XiaoJia849** [thuml/Time-Series-Library#529]
in 
https://github.com/thuml/Time-Series-Library/blob/6949146ca20c802ebba4e810e52405097cd672b1/layers/ETSformer_EncDec.py#L156

https://github.com/thuml/Time-Series-Library/blob/6949146ca20c802ebba4e810e52405097cd672b1/layers/ETSformer_EncDec.py#L176

device errors occur 
because the devices of index_tuple[0] index_tuple[1] index_tuple[2] index_tuple[3]
are  cpu cuda cpu cpu

**Comment by wuhaixu2016** [comment]
Hi, we have fixed this bug in the latest commit. Many thanks for your information.

**Comment by traverst** [comment]
Still not working for me.

I ended up adding        
` f = f.to(x_freq.device)
`
before 156 and also 
also modified 176:
`        index_tuple = (mesh_a.unsqueeze(1).to(x_freq.device), indices.to(x_freq.device), mesh_b.unsqueeze(1).to(x_freq.device))
`
